name: catalogmovie
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  dio: ^5.3.4
  provider: ^6.1.1
  get_it: ^7.6.4
  dartz: ^0.10.1
  carousel_slider: ^4.2.1
  infinite_scroll_pagination: ^4.0.0
  webview_flutter: ^3.0.4
  font_awesome_flutter: ^10.6.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

 
  assets:
    - assets/images/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
